name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@2.29.0

      - name: Validate composer.json and composer.lock
      run: composer validate

      - uses: ramsey/composer-install@2.2.0

      - name: Run tests with PHPUnit
        run: composer phpunit

      - name: Check coding standards with PHP_CodeSniffer
        run: composer phpcs
