name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # 環境構築
  build:
    # ubuntu 使う
    runs-on: ubuntu-latest

    steps:
			- uses: actions/checkout@v4

		- name: Setup PHP Action
      uses: shivammathur/setup-php@2.29.0

    - name: Validate composer.json and composer.lock
      # composer.json の文法や構文に問題がないか確認する
      run: composer validate

    - name: Install PHP Dependencies with Composer
      uses: ramsey/composer-install@2.2.0

    - name: Run tests with PHPUnit
      run: composer phpunit

    - name: Check coding standards with PHP_CodeSniffer
      run: composer phpcs
