name: learn-github-actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests with PHPUnit
        run: composer phpunit

      - name: Run tests with PHPCodeSniffer
        run: composer phpcs
