name: test

# イベント
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests with PHPUnit
        run: composer phpunit

      - name: Run tests with PHPCodeSniffer
        run: composer phpcs
