name: learn-github-actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests with PHPUnit
        run: ./vendor/bin/phpunit tests

      - name: Run tests with PHPCodeSniffer
        run: ./vendor/bin/phpcs --standard=phpcs.xml src tests
